.travis.yml
README.markdown
build.properties
build.xml

After merging this request, you'll need to do a few changes:
1. Create an new developer org and get the security token.
2. Go to travis-ci.org and add the repository
3. Follow the instructions at http://docs.travis-ci.com/user/encryption-keys/ to create secure environment variables for username and password
* SFUSER="username@something.com"
* SFPWD="password+token"
4. Update the .travis.yml file with the secured credentials above
5. Update the Readme.md with the correct build image

Continuous Integration Setup #131

---

rolluptool/src/classes/RollupCalculateController.cls
rolluptool/src/classes/RollupCalculateJob.cls
rolluptool/src/classes/RollupService.cls
rolluptool/src/classes/RollupServiceTest3.cls
rolluptool/src/pages/rollupcalculate.page

Add textarea to Calculate screen where a WHERE clause can optionally be
entered, allowing the master records to be filtered.

Allow Master Records To Be Filtered During Calculate

---

build.xml

Add undeploy target to ant build file to remove all DLRS metadata.

Add undeploy ant target

---

rolluptool/src/permissionsets/LookupRollupSummariesReadOnly.permissionset

Complication was breaking as classes have been removed in recent change to use fflib

readonly permission set regression from fflib upgrade

---

rolluptool/src/pages/welcome.page

Also changed the phrase a bit.

Fixing a typo with the 'utilize' word

---

rolluptool/src/classes/RollupService.cls

added “ORDER BY Id” into query string, resolves #518

responding to issue 518

---

README.markdown

The link took you to a version that would not install

Removed the link to the appexchange

---

force-app/main/classes/RollupCalculateJob.cls

Added organization Name and ID to error email

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
README.markdown
cumulusci.yml

This PR preps for Metecho onboarding.

Add CODEOWNERS, other cleanup

---

README.markdown

Added link to Community Sprint github repo for Doc and UX project work.

Updated to include link to Sprint repo

---

dlrs/main/classes/ManageLookupRollupSummariesNewTest.cls

Fix for failing test during beta package creation due to namespace in URLs

accounting for namespace in url assertion

---

cumulusci.yml

Add namespaced dev org for testing

---

dlrs/main/classes/MLRSControllerTest.cls

Fixes issues due to timezone / locale / formatting from #1193

test schedule agnostic of timezone/formatting

---

cumulusci.yml

Update flow definition

---

.github/workflows/beta.yml
.github/workflows/feature.yml
.github/workflows/prod.yml

This PR moves CI to GitHub Actions.

Convert CI to use GitHub Actions

---

cumulusci.yml
datasets/qa/mapping.yml
datasets/qa/qa_data.sql
unpackaged/config/qa/customMetadata/LookupRollupSummary2.QA_Apple_String_Concatenate.md-meta.xml
unpackaged/config/qa/customMetadata/LookupRollupSummary2.QA_Google_Sum_Revenue.md-meta.xml
unpackaged/config/qa/customMetadata/LookupRollupSummary2.QA_Salesforce_Count_Negotiation_Review.md-meta.xml
unpackaged/config/qa/triggers/AccountTrigger.trigger
unpackaged/config/qa/triggers/AccountTrigger.trigger-meta.xml
unpackaged/config/qa/triggers/OpportunityTrigger.trigger
unpackaged/config/qa/triggers/OpportunityTrigger.trigger-meta.xml

QA flow now creates test data.
Creates
* 8 Accounts
* 10 Opportunities for each Account
* Triggers and metadata for rollups
* Apple - Concatenating Opportunity Description into Account Description
* Google - Concatenating Opportunity Description into Account Description
* Salesforce - Count Opportunities where Stage = Negotiation/Review and places value in NumberOfEmployees

Test Data in QA Org Flow

---

dlrs/main/pages/managelookuprollupsummaries.page
dlrs/main/pages/managelookuprollupsummaries_New.page

Clarified phrasing of alert message

Fix phrasing of old tab alert message

---

docs/Installation/index.md

- new section on Calculation Sharing Mode in docs
Kudos @gokubi
Superseeds #1247

docs: Calculation Sharing Mode by @gokubi

---

dlrs/main/classes/RollupJob.cls

None
Updated Scheduled error email subject to match the standard Realtime one.
[#1219]

Updated scheduled error email subject

---

dlrs/main/pages/welcome.page

Swaps old Github documentation link for new documentation link
Closes #1235

Swap documentation link for correct link

---

package-lock.json
package.json

upgrading packages to force json5 security patch

---

cumulusci.yml

Don't attempt to remove test trigger when spidered into package

---

cumulusci.yml

Do not install unmanaged test triggers in beta/release orgs

---

dlrs/main/classes/CustomMetadataService.cls
dlrs/main/classes/ObjectSelectorController.cls-meta.xml
dlrs/main/classes/RollupEditorController.cls
dlrs/main/lwc/manageRollups/manageRollups.html
dlrs/main/lwc/manageRollups/manageRollups.js
dlrs/main/lwc/objectSelector/objectSelector.js
dlrs/main/lwc/rollupEditor/rollupEditor.html
dlrs/main/lwc/rollupEditor/rollupEditor.js
dlrs/main/permissionsets/LookupRollupSummariesFull.permissionset-meta.xml
dlrs/main/tabs/ManageLookupRollupSummaries2.tab-meta.xml

Huge amount of cleanup and merging efforts.
Get Deletes working (Still uses Session but using from an Async context to be compatible with LWC
Enable buttons and get them working correctly
Wire up object picker

pull it together and refactor code locations

---

cumulusci.yml

Install test triggers during release tests

---

dlrs/main/classes/RollupSummaries.cls
dlrs/main/classes/RollupSummariesTest.cls

Closing some ambiguity in how field validation is handled.
Bypassing some fflib "help" that causes relationship names to resolve to fields.
Adding in more tests focused on using CMDTs as well as exercising more validation logic.
#749

Improve field validation and increase CMDT tests

---

dlrs/main/pages/welcome.page

Update a couple urls that reference na1 for hyperforce migration.
#1357

Fix Hyperforce migration url issue

---

dlrs/main/classes/RollupSummariesTriggerTest.cls
dlrs/main/classes/RollupSummariesTriggerTest.cls-meta.xml

Add direct test coverage for trigger
#1364

Add direct tests for trigger coverage

---

dlrs/main/classes/RollupEditorController.cls
dlrs/main/lwc/manageRollups/manageRollups.js
dlrs/main/lwc/rollupEditor/rollupEditor.html
dlrs/main/lwc/rollupEditor/rollupEditor.js

Change use a wrapper class to communicate with the LWCs, enabling the LWCs to be mostly namespace agnostic.

Get working in namespaced orgs via abstraction

---

dlrs/main/lwc/manageRollups/manageRollups.js

Change to not directly import PE object and fields. They are corrupted by the platform. Instead import another object and use that to discover the namespace, if present.

Fix PE Imports

---

dlrs/main/lwc/manageRollups/manageRollups.js

Improve record interaction flows with by re-opening after record save.
#1445

Enable re-open after save

---

dlrs/main/lwc/rollupEditor/rollupEditor.js

Critical Changes
Fix error message text and wrap in array so error is displayed correctly.
Issues Closed
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/1443

Fix error message for outstanding rollup items

---

dlrs/main/lwc/classSchedulerModal/classSchedulerModal.html
dlrs/main/lwc/classSchedulerModal/classSchedulerModal.js
dlrs/main/lwc/classSchedulerModal/cronstrue.js

Tested working in Lightning Locker as in Lightning Web Security now.
Also cleanup errors and add loading spinner to existing jobs.
Should load from Static Resource when LWS is everywhere.
Change cronstrue lib to load as part of the component instead of from Static Resources
Also added loading spinner and cleaned up prop usage.
#1450

Direct load cronstrue in the LWC to make Locker happy

---

dlrs/main/lwc/classSchedulerModal/classSchedulerModal.js
dlrs/main/lwc/manageRollups/manageRollups.js
dlrs/main/lwc/rollupEditor/rollupEditor.js

Move toast handling out of modal and add error capture
#1452

Move toast handling out of Modal

---

dlrs/main/pages/welcome.page

Update OSS Credits for pre-existing software

update OSS credits

---

dlrs/main/classes/AsyncApexJobsSelectorTest.cls
dlrs/main/classes/AsyncApexJobsSelectorTest.cls-meta.xml
dlrs/main/classes/CustomMetadataService.cls
dlrs/main/classes/CustomMetadataServiceTest.cls
dlrs/main/classes/LookupRollupStatusCheckControllerTest.cls
dlrs/main/classes/LookupRollupStatusCheckControllerTest.cls-meta.xml
dlrs/main/classes/ObjectSelectorController.cls
dlrs/main/classes/ObjectSelectorControllerTest.cls
dlrs/main/classes/ObjectSelectorControllerTest.cls-meta.xml
dlrs/main/classes/RollupEditorControllerTest.cls
dlrs/main/classes/RollupEditorControllerTest.cls-meta.xml
dlrs/main/classes/SchedulerController.cls
dlrs/main/classes/SchedulerControllerTest.cls
dlrs/main/classes/SchedulerControllerTest.cls-meta.xml

Add Apex tests for code added to support the new LWC Wizard

Add tests for new LWC Wizard Apex

---

dlrs/main/classes/RollupSummariesTest.cls

* Improve error check for compatibility
#1489

Limit error message match

---

dlrs/main/classes/RollupServiceMergeTest.cls

Add feature gate to case merge tests

Gate tests on case merge being enabled

---

dlrs/main/classes/RollupServiceMergeTest.cls

Gate contact merge test when trigger is installed

Gate contact test when trigger is not installed

---

dlrs/main/applications/DeclarativeLookupRollupSummaries2.app-meta.xml

* Add DLRS to app name to increase searchability
* #1290

Add DLRS to app name to increase searchability
