rolluptool/src/classes/LREngine.cls
If the child field is null, then the split throws an exception.
=> Bug Fix for issue #150 - child field is null

rolluptool/src/classes/RollupServiceTest3.cls
Remove code to assign non-existent LookupRollupSummariesTest permission
set to the test user created in RollupServiceTest3.
=> Remove Invalid Permission Set from Test

rolluptool/src/classes/RollupController.cls, rolluptool/src/classes/RollupControllerTest.cls, rolluptool/src/classes/RollupServiceTest.cls, rolluptool/src/classes/RollupServiceTest2.cls, rolluptool/src/classes/RollupServiceTest3.cls, rolluptool/src/classes/RollupSummaries.cls, rolluptool/src/classes/RollupSummariesTest.cls, rolluptool/src/classes/Utilities.cls, rolluptool/src/classes/Utilities.cls-meta.xml, rolluptool/src/package.xml
Update code to run in orgs with no namespace or a namespace other than
"dlrs" by determining the namespace at run-time.
*The change from #176 is included in this pull request as well to allow for all tests to pass successfully in any dev org.  I've tested in a dev org with no namespace and one with a namespace other than `dlrs`.*
=> Make Namespace-Agnostic

rolluptool/src/classes/WelcomeController.cls, rolluptool/src/pages/welcome.page
Use the current namespace in the name of the Remote Site Setting record.
*This is useful if you have the managed package installed, and need to deploy the unpackaged code to the same org.*
=> Use Namespace In Remote Site Setting Name

rolluptool/src/classes/RollupSummaries.cls, rolluptool/src/classes/RollupSummariesTest.cls
Had two options here - refactor to a common validation method that is called by both flavors of onValidate or enable Configuration.OldOnUpdateValidateBehaviour.  Decided to go with the former to avoid legacy based code.
=> Issue212 rollup summary validations

rolluptool/src/classes/RollupService.cls, rolluptool/src/classes/RollupServiceTest.cls, rolluptool/src/classes/TestLREngine.cls
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/44f7a793b435faad4d635a8b12397d714ca41a1a for tests that demonstrate issue.
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/4e8c39c2bce37f6780a8420304c8c108c3df1de4 for proposed fix.
While I tackled this from the DLRS side, I think it makes sense to address this within LREngine as well by not having LREngine apply the "Then By" approach and instead not adding to the order by when detailOrderBy is null.  This PR works around that behavior when DLRS rollups have order by specified but still leaves open a gap when no order by is specified as when more rollups are added, order will change based on the way LREngine builds order by.  It's still non-deterministic in that …
=> issue #222 - incorrect result when same parent/child with different order by

rolluptool/src/classes/RollupService.cls, rolluptool/src/classes/RollupServiceTest3.cls
See Issue #196 and PR #208 for background
=> Add developer API to mirror triggerHandler behavior

rolluptool/src/classes/RollupService.cls, rolluptool/src/classes/RollupServiceTest4.cls, rolluptool/src/classes/RollupSummaries.cls
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/1633b4361687fcab0fd224bafcc141c5f2d35793 for tests that demonstrate issue.
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/023ae41f0219e8c82f589556862a57d5fff5b4eb for proposed fix.
Fix includes a proactive vs. reactive change to update all "Describable" LookupRollupSummary__c fields to their Describe name.  With this in place, the "toLowerCase" on the contextKey is not really needed (avoiding it would save some CPU cycles) but is included for legacy support as it would take an update to existing rollups to trigger the field values to be updated with proper describe names.  Not sure its possible (not too familiar with managed package installs) but possibly a …
=> Issue #229 - Ensure context is shared when rollups differ by case only

rolluptool/src/classes/RollupService.cls, rolluptool/src/classes/RollupServiceTest.cls, rolluptool/src/classes/RollupServiceTest3.cls, rolluptool/src/layouts/LookupChild__c-Lookup Child Layout.layout, rolluptool/src/layouts/LookupParent__c-Lookup Parent Layout.layout, rolluptool/src/objects/LookupChild__c.object
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/66b8e64aadd40b69eafb0f1a11134eb87db1eafc for tests that demonstrate issue.  Merging this commit in to existing code base separately will demonstrate failure.  This commit contains extra debug statements to make seeing expected vs. actual easier since asserts fail (set logging level to ERROR and look for %%LIMITS%%).
See commit https://github.com/jondavis9898/declarative-lookup-rollup-summaries/commit/e855153e8cf477b7e4cc20f5fc0c8bc5c7ca54fb for proposed fix.  This commit removes extra debug statements.
=> Issue #226 - Master records with no changes are updated

rolluptool/src/classes/RollupCalculateJobSchedulable.cls, rolluptool/src/classes/RollupCalculateJobSchedulable.cls-meta.xml, rolluptool/src/classes/RollupScheduledCalculateController.cls, rolluptool/src/classes/RollupScheduledCalculateController.cls-meta.xml, rolluptool/src/classes/RollupServiceTest3.cls, rolluptool/src/layouts/LookupRollupSummary__c-Lookup Rollup Summary Layout.layout, rolluptool/src/objects/LookupRollupSummary__c.object, rolluptool/src/package.xml, rolluptool/src/pages/rollupscheduledcalculate.page, rolluptool/src/pages/rollupscheduledcalculate.page-meta.xml, rolluptool/src/permissionsets/LookupRollupSummariesFull.permissionset
This code is a fully functional start point for the discussion in #142 based on @wes1278 's comment on scheduling a full recalculate.
My use case for this is to allow relative date literals to be used in roll up criteria.
=> allow full recalculates to be scheduled nightly

rolluptool/src/classes/LREngine.cls, rolluptool/src/classes/TestLREngine.cls
This pull request changes the data type requirements for First/Last Summaries to include Id and Reference as valid types. 
This change allows a user to have a summary result field be of type REFERENCE, and aggregate the Id of the first/last child into it, setting that lookup field.
An example:
Account has a lookup to "Largest Won Opportunity". The user would create a DLRS summary that aggregates Id into Largest_Won_Opportunity__c of Type "First" ordered by "Amount DESC" with a filter IsWon=True. 
This would set the largest won opportunity lookup on closure of a large opportunity. Then, the user could create formula fields or use other platform features to quickly get to details about that account's largest won opportunity.
A non-profit use case is setting the current program enrollment …
=> Allow First/Last Summaries to work on Id and Reference Fields

rolluptool/src/classes/RollupService.cls, rolluptool/src/classes/RollupServiceTest3.cls
Minor changes to prevent needing to check Active in order to do a manual
calculation when the Calculation mode is not Realtime.
=> Issue 359 resolved - Manual Calculate without marking Active

rolluptool/src/classes/LREngine.cls
Objects like `ContentDocumentLink` have implementation restrictions that prohibit empty query parameters on its parent fields `LinkedEntityId` or `ContentDocumentId`.
While troubleshooting this issue, I narrowed down the problem to `RollupService` line 163 where master record ids whose sobject type does not match that of the rollup's master type are filtered out. This likely doesn't happen often, but with `ContentDocumentLink` this happens every time a new File or Enhanced Note is created via the web UI when on a record detail page because two CDLs are created: one to share the new File/Note with the create user and one to share the new File/Note with the parent record (e.g. account or contact).
The error reported in issue #558 occurs when rollup calculation mode is **realtime** and the …
=> Fixes issue #558 by avoiding running query that won't have any masterRecordIds to filter by

.travis.yml
No need to have a wait parameter in the org create command. Plus, the minimum value is 3.
=> Fix wait param in org:create

.travis.yml, config/project-scratch-def.json
- Builds were failing due to 'force:org:create' command no longer accepting wait times of less than 5 seconds. 
- Org preferences have been replaced with scratch org settings and are deprecated starting with Winter'20.
=> Fix failing builds and replace deprecated org preferences

apex-ruleset.xml
Overrides PMD default to only include performance and security rules from https://github.com/pmd/pmd/tree/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule
=> init pmd ruleset

README.markdown
Added 2.15 install link - Points to MetaDeploy installer page https://install.salesforce.org/products/dlrs/latest
=> Added 2.15 install link

dlrs/main/classes/MLRSControllerTest.cls, dlrs/main/classes/ManageLookupRollupSummariesController.cls
I added the features outline in issue #1123. Attached are screenshots of how it looks when a user saves a record(create/update) and when a user loads a record.
-Amended the error message on save/update to inform the user that you can't activate a DLRS until the child trigger is deployed. And the "Active" checkbox needs to be unchecked when saving in this scenario.
Added a message on record load to make it clear if a trigger has been deployed or not:
1. Success(Green) indicator child and parent triggers are deployed.
2. Warning(orange) indicator if only a child or parent trigger is deployed.
3. Error(Red) indicator if neither child or parent trigger is deployed.
In response to #1123
#Screenshots
=> Feature: Amended error message on save/update to inform the user that you can't activate without deployment

dlrs/main/classes/CronTriggersSelector.cls, dlrs/main/classes/MLRSControllerTest.cls, dlrs/main/classes/ManageLookupRollupSummariesController.cls, dlrs/main/pages/managelookuprollupsummaries.page
I worked with @boopathiking1154 on this pull request to complete issue #1126. As the new wizard does not currently have edit capabilities, we added this feature to the current rollup wizard. Issue #1126 also asks for a view list of all scheduled rollups that has been added in #1131/#1183. 
Added field on Manage Lookup Rollup Summaries page "Scheduled Full Calculate - Next Date". This field returns the date of the next scheduled full calculate as a timestamp, if the end user has initiated a scheduled full calculate for the rollup summary. 
- Returns value as green text if schedule is found
- Returns value as red text if schedule is not found with message "No Schedule for Rollup".
#1126
=> Feature/apex scheduled #1126 Display on the new wizard if the apex is scheduled and what the schedule is

package-lock.json, package.json
Resolves dependabot issues for minimist.
Using `npm list minimist` I was able to identify the packages dependent on the problematic version of minimist (i.e. <v1.26.0)
```
├─┬ @salesforce/eslint-config-lwc@2.2.0
│ └─┬ @babel/core@7.15.8
│   └─┬ json5@2.2.0
│     └── minimist@1.2.5 deduped
├─┬ eslint-plugin-import@2.25.4
│ └─┬ tsconfig-paths@3.13.0
│   ├─┬ json5@1.0.1
│   │ └── minimist@1.2.5 deduped
│   └── minimist@1.2.5
└─┬ prettier-plugin-apex@1.10.0
└─┬ wait-on@5.3.0
└── minimist@1.2.5 deduped
```
I updated `eslint-config-lwc` to the latest version (I also updated  "eslint-plugin-aura" and "eslint-plugin-lightning"), which resolve d that dependency. However. eslint-plugin-import and prettier-plugin-apex are already at the latest version, so I had to force resolution to the fixed …
=> updating dependabot issues for minimist

dlrs/main/pages/managelookuprollupsummaries.page
@afawcett - Schedule Full Calculate: shows red text no schedule for rollup (though it does qualify “full” calculate - suggest making this text orangage or some “warning” level indicator)
Feedback from Andrew to change color of full calculate to orange. 
#Screenshot
=> UI feedback

dlrs/main/classes/RollupSummaryViewController.cls, dlrs/main/classes/RollupSummaryViewControllerTest.cls, dlrs/main/pages/RollupSummaryView.page
I changed the "Lookup Rollup List View" from the feedback from @afawcett.
- Renamed the title to "List View - All Lookup Rollup Summaries" indicating that the tab shows all rollups - not just scheduled rollups.
- Changed the "scheduled to run time" to "SCHEDULED FULL CALCULATE - NEXT DATE" with date formatted in the users local time.
=> Updated "Lookup Rollup List View" with changes from feedback

dlrs/main/classes/MLRSControllerTest.cls, dlrs/main/classes/ManageLookupRollupSummariesController.cls
Feedback changes from @afawcett testing document.
- Added the ability to toggle the informational messages on/off. 
- Added logic to hide messages if the rollup is already active.
- Changed warning level to indicate that the message as informational
=> UI - error prompt feedback changes

dlrs/main/classes/ManageLookupRollupSummariesNewController.cls
Mitigates bug in #1223 by filtering out EntityDefinitions where the following are false:
IsCustomizable
IsApexTriggerable
IsCustomSetting
#1223
=> adding filter on sobjects to mitigate issue with VF limit

dlrs/main/classes/CronTriggersSelector.cls
None
- Deleted Cron Triggers are filtered out in selectAll
-  Cron triggers select by Id is returning Scheduled Apex jobs only
[#1253]
=> Cron Trigger selector skip deleted jobs

README.markdown
Removed hard reference to a specific release (ie. 2.17) and pointed to the releases page instead
=> Update links to be generic

cumulusci.yml, dlrs/main/classes/RollupCalculateControllerTest.cls, dlrs/main/classes/RollupServiceTest4.cls, dlrs/main/classes/RollupServiceTest6.cls
Resolve test guards that should have been blocked but were seeing the packaged triggers and running.
Cleaned up one file and added standard guards to two others that were missing them.
#1364
=> Guard tests that depend on unpackaged triggers

dlrs/main/classes/RollupController.cls, dlrs/main/classes/RollupControllerTest.cls
Update RollupController (which backs the Trigger Deployment VF page) so it can auto-determine the max supported API version for the current org. This breaks a dependency we have on manually updating the package each release to support new objects.
#1373
=> enable RollupController get API version from org

dlrs/main/lwc/autocompleteCombobox/autocompleteCombobox.html, dlrs/main/lwc/autocompleteCombobox/autocompleteCombobox.js, dlrs/main/lwc/autocompleteCombobox/js-levenshtein.js, dlrs/main/lwc/objectSelector/objectSelector.html, dlrs/main/lwc/objectSelector/objectSelector.js, dlrs/main/lwc/rollupEditor/rollupEditor.html, dlrs/main/lwc/rollupEditor/rollupEditor.js
- Utilize autocomplete combobox for object selector
- Disable field selection comboboxes in rollup editor when no options are available
- Remove onmouseleave behavior from autocomplete combobox
- Decouple show/hide behavior in autocomplete combobox to manage visibility independently
- Add property to configure "disable" behavior on autocomplete combobox
- Add ability to specify a search threshold on the autocomplete combobox
- Display configurable message when no autocomplete options are available
- Add autocomplete combobox property to indicate the maximum number of search results that are displayed
- Add autocomplete combobox property to indicate that search is required to display options
- Update selectOptionByValue function to identify options based on exact match
- Use levenshtein …
=> Autocomplete Combobox Enhancements

dlrs/main/classes/RollupService.cls
Ignore duplicate value error on Schedule Items caused by sharing isolation
#375
=> ignore DUPLICATE_VALUE on sched item errors

dlrs/main/lwc/manageRollups/manageRollups.html, dlrs/main/lwc/manageRollups/manageRollups.js
- Utilize LWC Datatable actions to filter by `Rollup Type`, `Calc Mode`, and `Active` in the primary datatable view
- Display the SLDS `utility:filterList` icon in the column header when a columns is actively being filtered
- The search filter continues to work in conjunction with the column filters
- #1449
=> Datatable Column Filters

dlrs/main/classes/RollupService.cls
- Fixed an issue where `DUPLICATES_DETECTED` errors were incorrectly thrown during DML operations, even when duplicates were allowed.
- Added `dml.OptAllOrNone = allOrNothing` to ensure proper handling of DML operations based on the `allOrNothing` flag.
- Adjusted `DMLOptions` to allow saving records with duplicates when `allowSave` is set.
- Resolved failures caused by duplicate rules during DML operations.
- Ensured consistent handling of duplicate records based on configured rules.
=> Fix duplicate detection issue by applying DML options with all-or-nothing behavior

dlrs/main/classes/BypassHandler.cls, dlrs/main/classes/BypassHandlerTest.cls, dlrs/main/classes/RollupCalculateJob.cls, dlrs/main/classes/RollupCalculateJobTest.cls, dlrs/main/classes/RollupEditorController.cls, dlrs/main/classes/RollupJob.cls, dlrs/main/classes/RollupJobTest.cls, dlrs/main/classes/RollupService.cls, dlrs/main/classes/RollupServiceTest.cls, dlrs/main/classes/RollupSummariesSelector.cls, dlrs/main/classes/RollupSummary.cls, dlrs/main/classes/RollupSummaryTest.cls, dlrs/main/classes/RollupSummaryTest.cls-meta.xml, dlrs/main/classes/Utilities.cls, dlrs/main/classes/UtilitiesTest.cls, dlrs/main/classes/UtilitiesTest.cls-meta.xml, dlrs/main/layouts/LookupRollupSummary2__mdt-Lookup Rollup Summary Layout.layout-meta.xml, dlrs/main/lwc/rollupEditor/rollupEditor.html, dlrs/main/lwc/rollupEditor/rollupEditor.js, dlrs/main/objects/DeclarativeLookupRollupSummaries__c/fields/DisableDLRSGlobally__c.field-meta.xml, dlrs/main/objects/LookupRollupSummary2__mdt/fields/BypassPermissionApiName__c.field-meta.xml, unpackaged/config/test/customPermissions/DisableDLRS.customPermission-meta.xml, unpackaged/config/test/permissionsets/DisableDLRS.permissionset-meta.xml
* Allow DLRS to be disabled globally using new Custom Setting field
* Allow DLRS to be disabled globally using new Apex API method: `RollupService.bypassAll()`
* Allow individual Rollups to have a Custom Permission assigned that, when held by the user, will disable that rollup
#1469
#786
#468
=> Allow greater control to disable DLRS globally or in specific cases

dlrs/main/classes/RollupCalculateJobTest.cls, dlrs/main/classes/RollupJobTest.cls, dlrs/main/classes/Utilities.cls, dlrs/main/classes/UtilitiesTest.cls
* improve custom permission check to work in packaged context
#1507
=> Change check permission strategy

dlrs/main/classes/RollupCalculateJobTest.cls, dlrs/main/classes/RollupJobTest.cls, dlrs/main/classes/UtilitiesTest.cls
Additional commit to fix test code. Missed this on the first refactor.
=> Correcting tests for custom permission

dlrs/main/classes/RollupService.cls, dlrs/main/classes/RollupServiceMergeTest.cls, dlrs/main/classes/RollupServiceMergeTest.cls-meta.xml, dlrs/main/classes/RollupSummariesSelector.cls, orgs/beta.json, orgs/beta_prerelease.json, orgs/dev.json, orgs/dev_prerelease.json, orgs/feature.json, orgs/release.json
* bugfix: refactor merging to better support case merge and keep scenario 
* #1038
=> Refactor handleRollups because merging could fail
